### ISSUE TITLE
Inverted artist names (e.g. lastname, firstname) will cause searches to fail

### ISSUE THREAD

**Issue by classicjazz** [regosen/get_cover_art#12]
**Problem**
Inverted artist names (e.g. lastname, firstname) will cause searches to fail

**Details**
Artist info may be correct but presented lastname, firstname. This is particularly an issue with classical recordings.

I am not sure that there is an easy solution because many artists have commas in their names

**Comment by regosen** [comment]
I just pushed a new version of get_cover_art (v 1.4.4) that should address this pretty cleanly.  Let me know if you encounter any side effects.
