### ISSUE TITLE
Add top-level script.

### ISSUE THREAD

**Issue by vext01** [regosen/get_cover_art#15]
(great project! Thank you)

It would be more user-friendly if when you install `get_cover_art` a script is installed in `bin/` so that instead of:

```
python -m get_cover_art ...
```

Users run:
```
get_cover_art ...
```

Thanks

**Comment by regosen** [comment]
Hi, that sounds like an easy win, but I'm not familiar with how to achieve this.  Can you point me to another github project that does this?  I'll use that as reference.  Thanks!

**Comment by vext01** [comment]
I think you'd usually do it in your `setup.py` script (or `setup.cfg`).

You need to define an entry point. Docs [here](https://setuptools.pypa.io/en/latest/userguide/entry_point.html).

Examples:

 - [nanodlna](https://github.com/gabrielmagno/nano-dlna/blob/ea5b166ac83f165fef7a920705e2301d9d22ab8d/setup.py#L47-L51)
 - [py.test](https://github.com/pytest-dev/pytest/blob/bcad6e8e9a57af22eca1e799897003fa5ebfffd3/setup.cfg#L62-L65)
 - [sphinx](https://github.com/sphinx-doc/sphinx/blob/4c91c038b220d07bbdfe0c1680af42fe897f342c/setup.py#L237-L243)

**Comment by regosen** [comment]
Thanks for the examples, that helps a lot!  I just uploaded v1.4.10 to pypi with these changes, and I _think_ it should work, but I'm not used to your use case.  

Can you try `pip install get_cover_art --upgrade` and give it a shot?  If it works, I'll git push my changes as well.

**Comment by vext01** [comment]
Hi,

Thanks for the fast response.

The script is being installed correctly, but something is wrong with your dependencies.

On a system that i've not installed `get_cover_art` on yet:
```
$ pip3.8 install get_cover_art
Defaulting to user installation because normal site-packages is not writeable
Collecting get_cover_art
  Downloading get_cover_art-1.4.10-py3-none-any.whl (20 kB)
Installing collected packages: get-cover-art
Successfully installed get-cover-art-1.4.10
$ ~/.local/bin/get_cover_art 
Traceback (most recent call last):
  File "/home/edd/.local/bin/get_cover_art", line 5, in <module>
    from get_cover_art import main
  File "/home/edd/.local/lib/python3.8/site-packages/get_cover_art/__init__.py", line 1, in <module>
    from .cover_finder import CoverFinder
  File "/home/edd/.local/lib/python3.8/site-packages/get_cover_art/cover_finder.py", line 5, in <module>
    from .meta.meta_mp3 import MetaMP3
  File "/home/edd/.local/lib/python3.8/site-packages/get_cover_art/meta/meta_mp3.py", line 2, in <module>
    from mutagen.mp3 import MP3
ModuleNotFoundError: No module named 'mutagen'
```

Did you list your dependencies in `setup.py` (or in a `requirements.txt`)?

See [these docs](https://python-packaging.readthedocs.io/en/latest/dependencies.html).

**Comment by regosen** [comment]
Ah, thanks for trying this out.  I just discovered I can use `python setup.py develop` to test locally.  Can you try upgrading to 1.4.11 and try it again?

**Comment by vext01** [comment]
I saw it install mutagen this time. LGTM :)

Thanks!

**Comment by vext01** [comment]
By the way, where are you making these changes? I can't see the commits.

**Comment by regosen** [comment]
I was holding out from pushing until you verified the fix, pushed now.

(Until now I've excluded setup.py from the repo because it includes the version number and changing that would be a lot of noise... but I'm reading now of ways around that, so I'll introduce setup.py soon)

**Comment by vext01** [comment]
I wouldn't worry about the noise. It's standard practice to include version bump commits. Then the whole process is reproducible for third parties.

**Comment by regosen** [comment]
Fair point, added!
