### ISSUE TITLE
Document and add the ability to control `skip_artwork.txt`

### ISSUE THREAD

**Issue by vext01** [regosen/get_cover_art#17]
I noticed that `get_cover_art` writes a `skip_artwork.txt` file which causes directories to be skipped on a rerun.

This file doesn't seem to be documented. I'd also like to ability to disable writing such a file.

Thanks!

**Comment by regosen** [comment]
Good idea, I just added a --no_skip option that disables writing and using such a file.  I also updated the documentation to better explain behavior around skip_artwork.txt

**Comment by vext01** [comment]
So to be clear, `--no-skip` will not cause covers already in the cache to be re-downloaded?

You are gonna kick yourself, but some of the args to `get_cover_art` are like `--this_with_underscores` and others are like `--this-with-hyphens`.

At first I tried `--no-skip` and got confused. It's `--no_skip`.

Probably too late to fix now.

**Comment by regosen** [comment]
Ack, good catch.  I'm switching them now to all be with hyphens (but still support underscore versions under the hood to be backwards-combatible)

`--no-skip` means it will ignore `skip_artwork`
