### ISSUE TITLE
Failed to find matching artist ({meta_artist}) and album ({meta_album})

### ISSUE THREAD

**Issue by classicjazz** [regosen/get_cover_art#19]
I notice in 1.5.5 in verbose mode the following over and over for albums that lack existing embedded album art:

**Failed to find matching artist ({meta_artist}) and album ({meta_album})**

I don't know whether that is simply a cosmetic bug in what's written to the screen or whether get_cover_art is actually trying to search Apple Music for the strings ({meta_artist}) and ({meta_album})

**Comment by regosen** [comment]
Oops, thanks for catching this!  I recently switched our string conventions to use template strings and broke the convention in a couple places.  Please try again with the latest version (1.5.6)

In your case it should still print those errors, but this time it will display the actual artist and album names that it's searching with, based on the meta tags of your files.

**Comment by classicjazz** [comment]
That fixes the issue I reported. 

Thank you.
