### ISSUE TITLE
Feature request: get largest cover art available from Apple Music

### ISSUE THREAD

**Issue by audiomuze** [regosen/get_cover_art#20]
Currently the app pulls 500x500 cover art, whereas Apple often has 3000x3000 and sometimes 3600x3600 high resolution images available.  Could you add the option to pull the highest resolution apple has available?  It generally takes the form of:

URL returned by API:
https://is4-ssl.mzstatic.com/image/thumb/Music116/v4/0a/15/17/0a1517fa-6b1f-ca8a-36ef-05ab293432c0/802644832968.jpg/1000x1000bb.webp

URL of largest instance:
https://is4-ssl.mzstatic.com/image/thumb/Music116/v4/0a/15/17/0a1517fa-6b1f-ca8a-36ef-05ab293432c0/802644832968.jpg/9999x9999bb.jpg

**Comment by regosen** [comment]
This is a great idea!  I just added a new option to the script called "art-size" that will take any number and use the corresponding URL.  e.g. 1000 would result in pulling the first link in your example, and 9999 would result in the second link.

If you update get_cover_art to version 1.5.7 you should be able to use the new option.  Let me know how it goes!

**Comment by audiomuze** [comment]
Seems to be working as intended.  Thanks!
