### ISSUE TITLE
filename passed to --external-art-filename is ignored and artist - album is used instead

### ISSUE THREAD

**Issue by audiomuze** [regosen/get_cover_art#22]
I just ran ```get_cover_art --no-embed --art-dest-inline --art-size 9999 --external-art-filename xfolder.jpg --verbose``` expecting to see xfolder.jpg in all folders successfully processed.  The album covers were retrieved but rather than being named xfolder.jpg they all took the form of ```{artist} - {album}.jpg```

**Comment by regosen** [comment]
`--external-art-mode` and `--external-art-filename` were implemented by another person and I still don't understand it very well. @SumnerH would you mind having a look?

**Comment by SumnerH** [comment]
Sure. I'm looking at this now, and I'm not sure if it should be considered a bug or not—I'm open to discussion about it.

Short answer: I believe that audiomuze wants the `--art-dest-filename` flag and not `--external-art-filename`, and that using that will fix their issue.

Longer answer:  `--external-art-mode` is meant to allow the use of images that you already have from another source, either in preference to fetching art or as a fallback if `get_cover_art` can't find something. It doesn't affect the name of fetched images at all.

Suppose that you have a bunch of albums in different directories, many of which have a `cover.jpg` but some don't.  

You can use `--external-art-filename cover.jpg --external-art-mode before` to embed the existing `cover.jpg` images into each song (if they exist), and only fetch art when there is no local image file.  The `--external-art-filename` only affects the name of the file looked at for non-fetched images.

But when you're fetching an image, then the `--art-dest-filename` flag is what determines the name it's saved under.

**Comment by SumnerH** [comment]
So, yeah, @audiomuze please try `--art-dest-filename` instead and let us know whether that solves your issue.

**Comment by audiomuze** [comment]
@SumnerH, seems that in my haste I'd overlooked ```--art-dest-filename``` - all sorted.  Thanks!

**Comment by regosen** [comment]
Thanks all!  Closing this issue.
