### ISSUE TITLE
Add support for DSF files

### ISSUE THREAD

**Issue by audiomuze** [regosen/get_cover_art#28]
As DSF audio is increasingly common, supports ID3 tagging and is a supported format in Mutagen it'd be much appreciated if DSF support could be added.

**Comment by regosen** [comment]
I've never seen a DSF audio file before, would you mind sending me a link to one that I could use?

**Comment by audiomuze** [comment]
Here's a direct link to one: http://www.lindberg.no/hires/test/2L-125_stereo-2822k-1b_04.dsf.zip

Plenty to choose from at http://www.2l.no/hires/

**Comment by regosen** [comment]
Ok, it turned out to be pretty clean integration, done!  DSF support added in 1.6.0
