### ISSUE TITLE
Enhancement: option to download even if already embedded

### ISSUE THREAD

**Issue by pidiggy** [regosen/get_cover_art#3]
The Synology Audio Station requires jpg file in the same folder as album (not embedded in mp3 file).

Appears that if CoverFinder.scan_file finds artwork embedded in the mp3 file, it skips the download even with --test option is set.

Perhaps it could download the album cover art when a new "album_art" option is set true even if there is art-work embedded in the file.

**Comment by regosen** [comment]
I like this idea, I'll try adding a "force" option, will update you when it's live.  Would it be okay if the "force" option replaced existing embedded artwork (as opposed to adding additional embedded art to the mp3 file)?

**Comment by regosen** [comment]
This should be fixed as well now- if you run with --force at the commandline (or set `force` to True for `CoverFinder()`), then it will allow downloading/embedding regardless of existing embedded artwork.

**Comment by pidiggy** [comment]
Ok thanks I will try it this weekend and give feedback.

**Comment by regosen** [comment]
Hi, can I close this issue?  I got confirmation from another user that `force` is working, but I wanted to check with you as well.

**Comment by tylerk86** [comment]
Most definitely! Thanks again and Happy New Year’s!

Tyler Kemp tylerkemp@icloud.com
