### ISSUE TITLE
Exception: missing XMP tags

### ISSUE THREAD

**Issue by PacoH** [regosen/get_cover_art#33]
I tried to use this on a folder of movie audio tracks and got `Exception: missing XMP tags` for each file. What does this mean?

**Comment by regosen** [comment]
For .m4a or .m4b files, it's assumed to have the following tags:
- '©ART' or 'aART' for artist
- '©alb' for album
- '©nam' for title

I'm not familiar with movie audio tracks though.  Can you send me an example of one you're using?

**Comment by PacoH** [comment]
No tags. I just extract the audio track of a movie with ffmpeg. I can find cover art with Google images and add it with `mp4art --add cover.jpg track.m4a`. I just though automatically downloading the art would be nice but I didn't think it would require adding these other tags.

**Comment by Ar-Kareem** [comment]
I got the same issue with all the .m4a files that I have.

**Comment by regosen** [comment]
What tags do your .m4a files contain?  Can you send me an example?

**Comment by Ar-Kareem** [comment]
I attached an example .m4a to an email to you.

**Comment by regosen** [comment]
Thanks, I just had a peek at the file.  It only has a "TRACKTITLE" tag that contains both the artist name and the title combined.  get_cover_art doesn't try any clever parsing of the title track to separate a potential artist name from it.  It expects the separate artist tag to be set to something.  

If all your .m4a files are like this, that would explain why get_cover_art cannot work with them.
